name: ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6.x', '2.5.x', '2.4.x' ]
    steps:
    - uses: actions/checkout@master
    - name: Install packages
      run: |
        # 2019.12.13 below doesn't work
        # sudo apt-get -qy update
        sudo apt-get -qy install libgdbm5 libgdbm-dev
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Set up Bundler
      run: gem install bundler --no-document
    - name: Install dependencies
      run: bundle install
    - name: Compile
      run: |
        rake compile
    - name: Test
      run: |
        rake test
